version: 0.2

phases:
  install: 
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
  pre_build:
    commands:
      - pip install --upgrade awscli
      - npm install
  build:
    commands:
      - sh -ac '. ./.env.development
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build $S3_BUCKET 

